import Link from "next/link";
import { Logo } from "@/components/logo";

export const metadata = {
  title: "Terms of Service — Premise",
  description: "Terms of Service for Premise by Roadshow Creative.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border px-6 py-4">
        <div className="max-w-3xl mx-auto">
          <Link href="/">
            <Logo />
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-12">
          Last updated: March 2026
        </p>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-lg font-semibold mb-3">
              1. Agreement to Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using Premise ("the Service"), operated by
              Roadshow Creative, you agree to be bound by these Terms of
              Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              2. Description of Service
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Premise is an AI-powered technical scoping tool that generates
              proposal-ready scope documents from project briefs. The Service is
              intended for use by design agencies, freelancers, and technical
              teams.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              3. Accounts and Eligibility
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You must be at least 18 years old to use Premise. You are
              responsible for maintaining the security of your account
              credentials and for all activity that occurs under your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              4. Free and Paid Plans
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Premise offers a free tier limited to 2 lifetime scope
              generations. The Pro plan ($29/month or $24/month billed annually)
              provides unlimited scope generation, scope history, and PDF
              export. Free tier limits are based on lifetime usage and are not
              restored by deleting scopes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              5. Billing and Cancellation
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Pro subscriptions are billed in advance on a monthly or annual
              basis. You may cancel at any time through your account settings.
              Cancellation takes effect at the end of the current billing
              period. We do not offer refunds for partial billing periods except
              where required by law.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              6. AI-Generated Content
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Scope documents generated by Premise are produced by AI and are
              provided for informational and planning purposes only. They do not
              constitute professional legal, financial, or technical advice. You
              are solely responsible for reviewing, editing, and validating any
              output before using it in client proposals or contracts. Roadshow
              Creative makes no warranties regarding the accuracy, completeness,
              or fitness for purpose of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">7. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree not to use Premise to generate content that is unlawful,
              harmful, or violates the rights of others. You may not attempt to
              reverse engineer, resell, or redistribute the Service or its
              outputs at scale without written permission from Roadshow
              Creative.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              8. Intellectual Property
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You retain ownership of the project descriptions and briefs you
              submit. Roadshow Creative retains ownership of the Premise
              platform, its design, and underlying systems. Scope documents
              generated on your behalf may be used freely in your own client
              work.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              9. Limitation of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, Roadshow Creative shall
              not be liable for any indirect, incidental, special, or
              consequential damages arising from your use of Premise. Our total
              liability to you for any claim shall not exceed the amount you
              paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">10. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update these Terms at any time. Continued use of Premise
              after changes are posted constitutes acceptance of the revised
              Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">11. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              Questions about these Terms?{" "}
              <a
                href="mailto:hello@roadshowcreative.dev"
                className="text-primary hover:underline"
              >
                Email us
              </a>
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-border py-8 px-6">
        <div className="max-w-3xl mx-auto flex gap-6 text-xs text-muted-foreground">
          <Link
            href="/terms"
            className="hover:text-foreground transition-colors"
          >
            Terms of Service
          </Link>
          <Link
            href="/privacy"
            className="hover:text-foreground transition-colors"
          >
            Privacy Policy
          </Link>
        </div>
      </footer>
    </div>
  );
}
