import { notFound, redirect } from "next/navigation";
import { auth } from "@clerk/nextjs/server";
import { createServerClient } from "@/lib/supabase";
import { MarkdownRenderer } from "@/components/markdown-renderer";
import { PrintTrigger } from "@/components/print-trigger";
import type { Scope } from "@/lib/supabase";
import type { SessionClaims } from "@/types/auth";

const PLATFORM_LABELS: Record<string, string> = {
  "web-app": "Web app",
  "marketing-site": "Marketing site",
  "mobile-app": "Mobile app",
  ecommerce: "E-commerce",
  "api-backend": "API / backend",
  other: "Other",
  unknown: "Platform TBD",
};

const BUDGET_LABELS: Record<string, string> = {
  "under-10k": "Under $10k",
  "10k-50k": "$10k–$50k",
  "50k-100k": "$50k–$100k",
  "100k-plus": "$100k+",
  unknown: "Budget TBD",
};

export default async function PrintScopePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const { userId, has, sessionClaims } = await auth();

  const isPro =
    has({ plan: "pro" }) ||
    (sessionClaims as SessionClaims)?.metadata?.special_access === true;

  if (!isPro) redirect(`/scope/${id}`);

  const supabase = createServerClient();
  const { data: scope } = await supabase
    .from("scopes")
    .select("*")
    .eq("id", id)
    .eq("user_id", userId!)
    .single();

  if (!scope) notFound();

  const s = scope as Scope;
  const platform = s.input?.platform
    ? (PLATFORM_LABELS[s.input.platform] ?? s.input.platform)
    : null;
  const budget = s.input?.budget
    ? (BUDGET_LABELS[s.input.budget] ?? s.input.budget)
    : null;
  const date = new Date(s.created_at).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <>
      <PrintTrigger />
      <div className="bg-white text-zinc-900 min-h-screen">
        <div className="max-w-3xl mx-auto px-10 py-12">
          {/* Document header */}
          <div className="flex items-center justify-between mb-8 pb-5 border-b border-zinc-200">
            <div className="flex items-center gap-2">
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="#6366F1"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <circle cx="12" cy="12" r="10" />
                <circle cx="12" cy="12" r="1" />
                <line x1="12" y1="2" x2="12" y2="6" />
                <line x1="12" y1="18" x2="12" y2="22" />
                <line x1="2" y1="12" x2="6" y2="12" />
                <line x1="18" y1="12" x2="22" y2="12" />
              </svg>
              <span className="font-semibold text-sm tracking-tight text-zinc-900">
                Premise
              </span>
            </div>
            <span className="text-xs text-zinc-400">{date}</span>
          </div>

          {/* Title + metadata */}
          <div className="mb-8">
            <h1 className="text-2xl font-bold tracking-tight text-zinc-900 mb-3 leading-tight">
              {s.title || "Technical Scope"}
            </h1>
            <div className="flex flex-wrap items-center gap-3 text-xs text-zinc-500">
              {platform && (
                <span className="border border-zinc-200 rounded px-2 py-0.5 text-zinc-700">
                  {platform}
                </span>
              )}
              {budget && (
                <span className="border border-zinc-200 rounded px-2 py-0.5 text-zinc-700">
                  {budget}
                </span>
              )}
            </div>
          </div>

          {/* Original brief */}
          {s.input?.description && (
            <div className="mb-8 bg-zinc-50 border border-zinc-200 rounded-lg p-5">
              <p className="text-[10px] font-semibold text-zinc-400 uppercase tracking-widest mb-2">
                Original Brief
              </p>
              <p className="text-sm text-zinc-600 leading-relaxed">
                {s.input.description}
              </p>
            </div>
          )}

          {/* Scope output */}
          <div className="print-content not-dark">
            <MarkdownRenderer content={s.output} print />
          </div>

          {/* Footer */}
          <div className="mt-12 pt-5 border-t border-zinc-200 flex items-center justify-between">
            <span className="text-xs text-zinc-400">
              Generated by Premise · usepremise.app
            </span>
            <span className="text-xs text-zinc-400">{date}</span>
          </div>
        </div>
      </div>
    </>
  );
}
